#!/usr/bin/env python3
"""
Convert an 8 kHz / 8-bit unsigned PCM WAV into a C array for DAC playback
in DAC_ALIGN_8B_R mode. No resampling, no requantisation.

Stereo input is downmixed to mono (per-sample average); everything else
(non-8-bit, non-8 kHz) is rejected so the firmware never silently plays
the wrong rate.
"""
import argparse
import os
import sys
import wave


def load(path):
    with wave.open(path, "rb") as wf:
        n_ch = wf.getnchannels()
        sw = wf.getsampwidth()
        sr = wf.getframerate()
        n = wf.getnframes()
        raw = wf.readframes(n)
    if sw != 1:
        sys.exit(f"need 8-bit PCM, got {sw*8}-bit")
    if sr != 8000:
        sys.exit(f"need 8 kHz sample rate, got {sr} Hz")
    if n_ch == 1:
        return bytes(raw)
    mono = bytearray(len(raw) // n_ch)
    for i in range(len(mono)):
        acc = 0
        for c in range(n_ch):
            acc += raw[i * n_ch + c]
        mono[i] = acc // n_ch
    return bytes(mono)


def source_comment(source):
    if not source:
        return ""
    return f" * {source}\n"


def emit_c(samples, out_c, out_h, varname, source=None):
    n = len(samples)
    src = source_comment(source)
    with open(out_h, "w") as f:
        f.write(
            "/* Auto-generated by easteregg/wav_to_c.py - do not edit. */\n"
            + (f"/*\n{src} */\n" if src else "")
            + "#ifndef EASTEREGG_SAMPLES_H\n"
            "#define EASTEREGG_SAMPLES_H\n\n"
            "#include <stdint.h>\n\n"
            "#define EASTEREGG_SAMPLE_RATE_HZ 8000u\n"
            f"#define EASTEREGG_SAMPLES_LEN {n}u\n\n"
            f"extern const uint8_t {varname}[EASTEREGG_SAMPLES_LEN];\n\n"
            "#endif\n"
        )
    with open(out_c, "w") as f:
        f.write(
            "/* Auto-generated by easteregg/wav_to_c.py - do not edit. */\n"
            + (f"/*\n{src} */\n" if src else "")
            + '#include "easteregg_samples.h"\n\n'
            f"const uint8_t {varname}[EASTEREGG_SAMPLES_LEN] = {{\n"
        )
        line = "    "
        for b in samples:
            tok = f"0x{b:02x},"
            if len(line) + len(tok) + 1 > 80:
                f.write(line.rstrip() + "\n")
                line = "    "
            line += tok + " "
        if line.strip():
            f.write(line.rstrip() + "\n")
        f.write("};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("wav", help="input 8 kHz / 8-bit unsigned PCM .wav")
    ap.add_argument("--out-c", default="Core/Src/easteregg_samples.c")
    ap.add_argument("--out-h", default="Core/Inc/easteregg_samples.h")
    ap.add_argument("--var", default="samples_easteregg")
    ap.add_argument("--source", help="attribution text emitted as a comment in the generated files")
    args = ap.parse_args()

    samples = load(args.wav)
    print(f"loaded {len(samples)} samples ({len(samples)/8000:.2f} s)")
    os.makedirs(os.path.dirname(args.out_c) or ".", exist_ok=True)
    os.makedirs(os.path.dirname(args.out_h) or ".", exist_ok=True)
    emit_c(samples, args.out_c, args.out_h, args.var, args.source)
    print(f"wrote {args.out_c} and {args.out_h}")


if __name__ == "__main__":
    main()
