/* Auto-generated by easteregg/wav_to_c.py - do not edit. */
/*
 * sound data kindly provided by Telekom-Historik Museum Bochum, www.telekom-historik.de
 */
#ifndef EASTEREGG_SAMPLES_H
#define EASTEREGG_SAMPLES_H

#include <stdint.h>

#define EASTEREGG_SAMPLE_RATE_HZ 8000u
#define EASTEREGG_SAMPLES_LEN 39162u

extern const uint8_t samples_easteregg[EASTEREGG_SAMPLES_LEN];

#endif
